export {
  ChannelSchema,
  ClaimSchema,
  ClaimsFileSchema,
  CompanySchema,
  ContactSchema,
  DraftOutputSchema,
  DraftSchema,
  EventSchema,
  FactSchema,
  LeadSchema,
  LeadStateSchema,
  SCORE_THRESHOLD,
  SuppressionSchema,
  type Channel,
  type Claim,
  type ClaimsFile,
  type Company,
  type Contact,
  type Draft,
  type DraftOutput,
  type Fact,
  type Lead,
  type LeadState,
  type PipelineEvent,
  type Suppression,
} from "./schemas.js";
export { claimAllowlistPhrases, loadClaimsFile } from "./claims.js";
export {
  IllegalTransitionError,
  TERMINAL_STATES,
  assertTransition,
  canTransition,
  isTerminal,
} from "./state-machine.js";
export {
  migrate,
  openAndMigrate,
  openDatabase,
  type OutreachDb,
} from "./db.js";
export {
  addSuppression,
  ensureLead,
  findContactByEmail,
  findCompanyByDomain,
  getCompanyById,
  getContactById,
  getDraftById,
  getLatestDraftForLead,
  getLeadById,
  getPipelineStatus,
  insertContact,
  insertDraft,
  insertFact,
  isEmailSuppressed,
  isPaused,
  listContactsForCompany,
  listFactsForCompany,
  listLeadsByState,
  normalizeDomain,
  setPaused,
  transitionLead,
  unsubscribeEmail,
  updateDraft,
  updateLeadScore,
  upsertCompany,
  type EnsureLeadInput,
  type InsertContactInput,
  type InsertFactInput,
  type PipelineStatus,
  type UpsertCompanyInput,
} from "./repo.js";
